<a href="https://colab.research.google.com/github/samapatil1729/Machine-Learning-Practice/blob/main/MLP_week_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Practice Assignment 7

Common Data for Q1,Q2,Q3

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
text_data=['A metaverse is a network of 3D virtual worlds focused on social connection.',
           'In futurism and science fiction, the term is often described as a hypothetical iteration of the Internet as a single', 
           'universal virtual world that is facilitated by the use of virtual and augmented reality headsets.',
           'The term "metaverse" has its origins  the 1992 science fiction novel Snow Crash as a portmanteau of "meta" and "universe."',
           'Various metaverses have been developed for popular use such as virtual world platforms like Second Life.',
           'Some metaverse iterations involve integration between virtual and physical spaces and virtual economies',
           'often including a significant interest in advancing virtual reality technology.', 
           'The term has seen considerable use as a buzzword for public relations purposes to exaggerate development progress for various related technologies and projects.[10] Information privacy and user addiction are concerns within metaverses',
           'stemming from challenges facing the social media and video game industries as a whole.']

##Question 1

Vectorize the given text data using countvectorizer() object. What is the shape of text_data after vectorization?

(9,99)

(99,9)

(1,99)

(9,20)

None of them

**Ans: (9, 99)**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
ct = CountVectorizer()
text_1 = ct.fit_transform(text_data)
text_1.shape

(9, 99)

##Question 2

What is the shape of text_data after vectorization after the term that appeared in less than 2 documents are ignored?


(9,99)

(99,9)

(9,20)

(20,9)

None of them

**Ans: (9, 20)**

In [ ]:
ct2 = CountVectorizer(min_df=2)
text_2 = ct2.fit_transform(text_data)
text_2.shape

(9, 20)

##Question 3

What is the token associated with word "metaverse"?

50

51

52

53

None of them

**Ans: 51**

In [ ]:
ct.vocabulary_['metaverse']

51

##Question 4

Docs = ['This is the first question.', 'This document is the second document.', 'And this is the third one' ]

Write a code to convert the above text into an array after tokenizing it using countvectorizer with 10 features. What will be the output?



**Ans:**


array([[0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 1, 1]])


In [ ]:
Docs = ['This is the first question.', 'This document is the second document.', 'And this is the third one' ]

In [ ]:
cv = CountVectorizer()
x = cv.fit_transform(Docs)
x.toarray()

array([[0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 1, 1]])

##Question 5

Define a function called k_closest in python with the following signature:
           Which returns closest vectors in X which are closest to the vector p. Use the appropriate sklearn methods.

    Consider, X = np.asarray([[72, 69 ,82], [ 9 ,79, 99], [20 ,47, 88], [80 ,64, 49]]) p= np.asarray([[0,0,0]]) and k=1 For these values, what is the output of the function?

array([[20, 47, 82]])

array([[80 ,64, 49]])

array([[9 ,79, 99]])

array([[20 ,47, 88]])

**Ans: array([[20, 47, 88]])**

In [ ]:
from sklearn.neighbors import NearestNeighbors
np.random.seed(0)

In [ ]:
def  k_closest(X, p, k = 1):
  NB = NearestNeighbors()
  Xcl = NB.fit(X)
  idx = Xcl.kneighbors(p, k, return_distance=False)
  return X[idx[0]]

In [ ]:
X = np.asarray([[72, 69 ,82], [ 9 ,79, 99], [20 ,47, 88], [80 ,64, 49]])
p= np.asarray([[0,0,0]])
k_closest(X, p, k=1)

array([[20, 47, 88]])

##Question 6

### **Que 6.**
 Define a function called *distance* in python with the following signature:

```
def distance( x0 : "A vector as np.array", X: "A list of vectors as np.ndarray", p : "p value for Minkowsky distance. Default 2, for Eucledian"): 
```
which returns a list of calculated Minkowsky distances between the point x0 and all points in X. Recall that the p-Minkowsky distance between $\mathbf {x} = (x_1, x_2, \ldots x_n)^T$ and $\mathbf {y} = (y_1, y_2, \ldots y_n)^T$ is 


$$\delta(\mathbf x,\mathbf y) = \left( |x_1 - y_1|^p+ |x_2 - y_2|^p + \cdots + |x_n - y_n|^p \right )^{\frac{1}{p}}$$

Do not use any predefined function to calculate the same.

Consider,
X0 = np.array([1,0,0,0]),
X= np.asarray([[1, 0, 0,0], [0, 1, 1,1],[1,2,0,0]]),
p= 2
then,  what is the output of the function distance(X0,X,p) ?

Options: <br>

1. [0, 1, 0,1]

2. [1, 0, 0,0]

3. [0, 2, 2]

4. [0, 2, 1]

Ans: [0, 2, 2]

In [ ]:
def distance( x0, X, p= 2):
  
  if (X.shape[1] == 1) and (np.asarray(x0).size == 1) :  #if x0 is scalar and X is an array of scalars
      pass
  else:  assert x0.shape[0] == X.shape[1], "Input vectors must have identical dimension"

  assert p>0, "p must be positive integer"

  dist = lambda y : np.power(  np.sum(  np.power(  np.abs(x0-y)  ,p)  )  , 1/p  )

  return [dist(y) for y in X]

In [ ]:
X0 = np.array([1, 0, 0, 0])
X= np.asarray([[1, 0, 0, 0], 
               [0, 1, 1, 1],
               [1, 2, 0, 0]])
distance(X0, X, p=2)

[0.0, 2.0, 2.0]

Common data for Q7 to 11 Practice)

 Load digit dataset on Colab (datasets.load_digits()) and use softmax regression to build the model Using following steps.
 Step 1: Load the dataset and split it using train_test_split by keeping: test_size= 0.2 random_state=10

 Step 2: Use standard scaler as a scaling function to scale the training as well as test data.

 Step 3: Use Logisticregression() as an estimator and set parameter (multi_class='multinomial', solver='sag') to predict the output.

##Question 7

What is the shape of features data you got in digits dataset ?

**Ans: (1797, 64)**

In [ ]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import ConfusionMatrixDisplay, classification_report

In [ ]:
X, y = load_digits(return_X_y=True)

In [ ]:
X.shape

(1797, 64)

#Question 8

How many labels are there in the dataset?

**Ans: 10**

In [ ]:
len(np.unique(y))


10

##Question 9

How many times label '7' is there in the dataset?

**Ans: 179**

In [ ]:
pd.DataFrame(y).value_counts()

3    183
1    182
5    182
4    181
6    181
9    180
7    179
0    178
2    177
8    174
dtype: int64

In [ ]:
x_tr, x_te, y_tr, y_te = train_test_split(X, y,test_size = 0.2, random_state=10)

In [ ]:
pipe = make_pipeline(StandardScaler(), LogisticRegression(solver='sag', multi_class='multinomial'))

In [ ]:
clf = pipe.fit(x_tr, y_tr)
y_pred = clf.predict(x_te)
print(classification_report(y_te, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      0.91      0.94        34
           2       0.89      1.00      0.94        34
           3       1.00      0.95      0.97        40
           4       0.97      0.94      0.96        34
           5       0.94      1.00      0.97        32
           6       1.00      0.97      0.99        37
           7       1.00      1.00      1.00        40
           8       0.89      0.94      0.91        33
           9       1.00      0.95      0.97        39

    accuracy                           0.97       360
   macro avg       0.97      0.97      0.97       360
weighted avg       0.97      0.97      0.97       360



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_sag.py:354: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  ConvergenceWarning,


#**Graded Assignment - 7**


(Common data for Q1 to Q5 graded questions)

Step 1: Download the dataset using following link: (https://drive.google.com/file/d/1v-uxWEgTI0GDCOTZOX3shUMkTf1a_CL7/view?usp=sharing)

Step 2: Import the data in google colab using pd.read_csv().

Step 3: Seperate features and target data in seperate variable X and Y.

Step 4: Convert dataframe X and series y into array and save it in variable X_array,y_array.

Step 5: Split the dataset using train_test_split. (Keep parameter train_size=0.7 and random_state=10).

Step 6: Reshape the dataset in such a way that each entry of data has 90 samples.

Step 7: Use SGD regressor as an estimator and partial_fit to fit the dataset on the model. (Set random_state=10)

Step 8: Calculate different evaluation metrics value like mean_square_error, R2_score.

Use the training set for fitting the model and use the test data to make the predictions.

Note: No need to scale the data. It's already scaled.

Answer the below questions.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor

In [ ]:
urls='https://drive.google.com/file/d/1v-uxWEgTI0GDCOTZOX3shUMkTf1a_CL7/view?usp=sharing'
urls='https://drive.google.com/uc?id=' + urls.split('/')[-2]
df = pd.read_csv(urls)

##Question 1
How many fetaures are there in the dataset?


10

11

90,000

9000

**Ans: 10**

In [ ]:
df.shape

(90000, 11)

In [ ]:
df.head()

Feature-1  Feature-2  Feature-3  Feature-4  Feature-5  Feature-6  \
0     -1.580     1.0500      1.060     -0.440      0.451    -0.0348   
1     -0.832    -0.8660     -1.340      0.138      1.180     0.7330   
2     -0.237     2.0900     -3.930      0.296      0.352    -0.5010   
3     -1.170    -1.1300     -1.090      1.120      0.312     0.1830   
4      0.260    -0.0273      0.925     -1.150     -1.390     0.0251   

   Feature-7  Feature-8  Feature-9  Feature-10  Target  
0      0.643     0.2650      0.268      -0.851    84.7  
1     -1.410     0.1350     -0.088      -1.550  -211.0  
2      0.961    -0.0287      1.820       0.938   -96.9  
3      0.448    -0.8190     -1.010      -1.080  -152.0  
4      0.627     0.0950     -0.280      -0.848   -57.7

In [ ]:
X = df.iloc[:,:10]
Y = df.iloc[:,10]

In [ ]:
X_array = X.to_numpy()
y_array = Y.to_numpy()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_array, y_array, train_size = 0.9, random_state = 10)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((81000, 10), (9000, 10), (81000,), (9000,))

In [ ]:
X_train, X_test = X_train.reshape(-1,90,10), X_test.reshape(-1,90,10)
y_train, y_test = y_train.reshape(-1,90), y_test.reshape(-1,90)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((900, 90, 10), (100, 90, 10), (900, 90), (100, 90))

##Question 2

What is the value of intercept you got after training the model using SGDRegressor?(select the closest answer)

+0.005

-0.005

+0.105

-0.105

0

**Ans: -0.005**

In [ ]:
sgd = SGDRegressor(random_state = 10)
for i in range(X_train.shape[0]):
  X_batch, y_batch = X_train[i], y_train[i]
  sgd.partial_fit(X_batch, y_batch)

In [ ]:
sgd.intercept_

array([-0.0051044])

##Question 3

What is the value of cofficient corresponding to "feature-3"you got after trainig the model using SGDRegressor? (select the closest answer)

**Ans: 81.23**

In [ ]:
sgd.coef_

array([51.32117195, 22.26580455, 81.23785419, 53.19578104, 76.46592847,
       71.47197842, 93.45078666, 51.92184073, 30.03844346, 40.95696488])

##Question 4


What is the value of R2 score for test data

**Ans: 0.99**

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
y_pred = []
for j in range(X_test.shape[0]):
  y_preds = sgd.predict(X_test[j])
  y_pred.append(y_preds.tolist())

print("Test MSE      : {}".format(mean_squared_error(y_test, y_pred)))
print("Test R2 Score : {}".format(r2_score(y_test, y_pred)))

Test MSE      : 0.3111147496390788
Test R2 Score : 0.999991794553133


##Question 5

What is the value of cofficient corresponding to "feature-5" after 5th iteration.

**Ans: 57.04**

In [ ]:
regressor = SGDRegressor(random_state=10)
##Selecting data in batches
for i in range(X_train.shape[0]): 
    X_batch, y_batch = X_train[i], y_train[i]
    ## Partially fitting data in batches
    regressor.partial_fit(X_batch, y_batch)
    if i==5:
      break
print(regressor.coef_)

[41.24246245 16.19332644 60.46094414 36.84673741 57.04552765 56.74587642
 75.84279346 44.89331541 19.20575663 33.21598262]


##(Common data for Q6 to Q8 Graded questions)

This dataset was constructed by adding elevation information to a 2D road network in North Jutland, Denmark (covering a region of 185 x 135 km^2). Elevation values where extracted from a publicly available massive Laser Scan Point Cloud for Denmark. This 3D road network was eventually used for benchmarking various fuel and CO2 estimation algorithms. This dataset can be used by any applications that require to know very accurate elevation information of a road network to perform more accurate routing for eco-routing, cyclist routes etc. For the data mining and machine learning community, this dataset can be used as 'ground-truth' validation in spatial mining techniques and satellite image processing. It has no class labels,

Use this dataset to guess some missing elevation information for some points on the road.

Column names:

OSM_ID: OpenStreetMap ID for each road segment or edge in the graph.

LONGITUDE: Web Mercaptor (Google format) longitude

LATITUDE: Web Mercaptor (Google format) latitude

ALTITUDE: Height in meters.

Load the dataset from link("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt"). Set parameter chunk size=20000 and iterator =True in pd.read_csv().

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt"
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt", header = None)

In [ ]:
df.head()

0         1          2          3
0  144552912  9.349849  56.740876  17.052772
1  144552912  9.350188  56.740679  17.614840
2  144552912  9.350549  56.740544  18.083536
3  144552912  9.350806  56.740485  18.279465
4  144552912  9.351053  56.740486  18.422974

##Question 6

Check how many total samples are there in the dataset?

**Ans: 434874**

In [ ]:
df.shape

(434874, 4)

##Question 7

What is the value of intercept after 7th iteration. (select the closest option).

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
chunksize = 20000
regressor = SGDRegressor(random_state=10)
scaler  = StandardScaler()

for train_df in pd.read_csv(url,
                            chunksize=chunksize,
                            iterator=True):
    xtrain_partial = train_df.iloc[:, 1:3]
    ytrain_partial = train_df.iloc[:, 3]
    scaler.partial_fit(xtrain_partial, ytrain_partial) 


iter = 1
url_1 = "https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt"
for train_df in pd.read_csv(url_1,
                            chunksize=chunksize,
                            iterator=True):
  
    xtrain_partial = train_df.iloc[:, 1:3]
    ytrain_partial = train_df.iloc[:, 3]
    scaler.transform(xtrain_partial)
    regressor.partial_fit(xtrain_partial, ytrain_partial)
    if iter==7:
      print("After iter #", iter)
      print(regressor.intercept_) 
      print(regressor.coef_)
      break  
    iter = iter + 1

After iter # 7
[-3.3580229e+08]
[-1732780.23537162  6145752.04828986]


##(Common data for Q9 to 11)

Load Iris datset on Colab and use KNN classifier to build the model Using following steps.

Step 1: Load the dataset and split it using train_test_split by keeping: test_size= 0.2 random_state=10

Step 2: Use Normalizer() as a scaling function to scale the data.

Step 3: Use KNeighborsClassifier(K) as an estimator to predict the output.

In [ ]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import Normalizer
from sklearn.metrics import accuracy_score, f1_score

In [ ]:
X, y = load_iris(as_frame = True, return_X_y = True)

In [ ]:
X.shape

(150, 4)

In [ ]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size = 0.2, random_state = 10)

In [ ]:
X_tr.shape, X_te.shape, y_tr.shape, y_te.shape

((120, 4), (30, 4), (120,), (30,))

In [ ]:
N = Normalizer()
X_tr_norm = N.fit_transform(X_tr)
X_te_norm = N.fit_transform(X_te)

In [ ]:
X_tr_norm.shape

(1437, 64)

##Question 9

What is the accuracy for k=3?

0.96

0.91

0.99

1.0

**Ans: 0.96**

In [ ]:
for i in range(2,5):
  kn = KNeighborsClassifier(i)
  clf = kn.fit(X_tr_norm, y_tr)
  y_pred = clf.predict(X_te_norm)
  acc_score = accuracy_score(y_te, y_pred)
  print(f'Accuracey for K={i} is {acc_score}')

Accuracey for K=2 is 0.9666666666666667
Accuracey for K=3 is 0.9666666666666667
Accuracey for K=4 is 0.9666666666666667


##Question 11

Compute wieghted F1 score value for k=3.(Keep parameter average='weighted')

In [ ]:
kn = KNeighborsClassifier(3)
clf = kn.fit(X_tr_norm, y_tr)
y_pred = clf.predict(X_te_norm)
f1_score = f1_score(y_te, y_pred, average='weighted')
print(f'f1_score for K={3} is {f1_score}')

f1_score for K=3 is 0.9671111111111111
