<a href="https://colab.research.google.com/github/samapatil1729/Machine-Learning-Practice/blob/main/MLP_week_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Practice Assignment 8**

Write a function 


compute_score(X_train, y_train, X_test, y_test)

to do the following on the 

Iris dataset-

Write your code keeping in mind:

Split the Iris dataset into train and test set with 70:30 ratio

Import svm.SVC as 'model'

kernel as 'rbf', 
regularization parameter as 20 and 

gamma as 'auto'

random_state=42

Train the model using trining data and predict the computed model's score using test data.

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
np.random.seed(42)


##Question 1

Which of the following options is the computed score?



-1.0

-0.5

1.0

0.5

**Ans: 1.0**

In [ ]:
def compute_score(X_train, y_train, X_test, y_test):
  svc = SVC(gamma = 'auto', kernel='rbf', C = 20)
  clf = svc.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  print(f'Computed Score is {clf.score(X_test, y_test)}')

In [ ]:
X, y = load_iris(as_frame = True, return_X_y = True)

In [ ]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size = 0.3)

In [ ]:
compute_score(X_tr, y_tr, X_te, y_te)

Computed Score is 1.0


##Question 2


1 point
In 'Question 1', apply a pipeline containing a MinMaxScaler()function calledScaler and a svm.svc() called classifierwith the parameters : kernel='linear', decision_function_shape='ovr', C=1, class_weight=None. Calculate the precision value and f1 score and mark the correct option from the list below.

1.0, 1.0

0.8, 0.8

0.99, 0.99

0.97, 0.87

**Ans: 1.0, 1.0**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import f1_score, precision_score

In [ ]:
pipe = make_pipeline(MinMaxScaler(), SVC(kernel='linear', decision_function_shape='ovr', C=1, class_weight=None))
clf = pipe.fit(X_tr, y_tr)
y_pred = clf.predict(X_te)

In [ ]:
print('precision Score:', precision_score(y_te, y_pred, average='micro'))
print('f1 score: ', f1_score(y_te, y_pred, average='micro'))

precision Score: 1.0
f1 score:  1.0


##Question 3

Import the `iris` dataset and drop the rows where `class=Iris-versicolor`. Apply a pipeline containing a `MinMaxScaler()`function called`Scaler` and a `svm.svc()` called `classifier`. Split the `iris` dataset into 50:50 ratio with `random_state=0`. Mark the correct recall value from the given options.

(a) 1.00

(b) 0.22

(C) 0.96

(d) 2.33

**Option a**

In [ ]:
from sklearn.datasets import load_iris
df = load_iris(as_frame = True)
df1 = pd.DataFrame(df.data)
df1['classes'] = df['target']

In [ ]:
df1.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   classes  
0        0  
1        0  
2        0  
3        0  
4        0

In [ ]:
id = np.where(df1['classes'] == 1)

id

(array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),)

In [ ]:
df2 = df1.drop(index = [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
df2['classes'].value_counts()

0    50
2    50
Name: classes, dtype: int64

In [ ]:
df2.shape

(100, 5)

In [ ]:
X = df2.iloc[:,:-1]
y = y = df2.iloc[:,-1].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 0)

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
pipe = make_pipeline(MinMaxScaler(), SVC())
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
print('Recall: ', recall_score(y_test, y_pred, average='micro'))

Recall:  1.0


##Question 4
Write the function compute_score(X_train, y_train, X_test, y_test) to do the following on the Iris dataset-

Write your code keeping in mind:

Split the Iris dataset into train and test set with 70:30 ratio and random_state=42.
Import sklearn.svm.LinearSVC as 'model'
Consider loss function loss=hinge,random_state=42 and penalty=l2.
Train the 'model' and mark the computed 'score'

(a) 2.233333333333333

(b)0.9777777777777777

(c) 0.899999999999999

(d) -2.23333333333333

Option b

In [ ]:
from sklearn.svm import LinearSVC

In [ ]:
X, y = load_iris(as_frame = True, return_X_y = True)

In [ ]:
X.shape, y.shape

((150, 4), (150,))

In [ ]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [ ]:
def compute_score(X_train, y_train, X_test, y_test):
  model = LinearSVC(loss = 'hinge', penalty = 'l2', random_state = 42)
  model.fit(X_tr, y_tr)
  print('Computed Score:', model.score(X_te, y_te))

In [ ]:
compute_score(X_tr, y_tr, X_te, y_te)

Computed Score: 0.9777777777777777


/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


#Question 5

Write a function `hyperparameter_search`which accepts the Kernel and regularization parameter as inputs and returns the `avg_score`of the models with the below mentioned hyperparameters. 
- Split the Iris dataset into train and test set with 70:30 ratio 
- kernels = `['linear', 'rbf']`
- Regularization `C = [5, 10,100]`
- Cross Validation = 10
-`random_state=42`

Which of the following options give the `accuracy_score` for the `iris dataset`?

(a) -1

(b) -2

(c) 1

(d) 0.8

**Option C**

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris

In [ ]:
X, y = load_iris(as_frame = True, return_X_y = True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

In [ ]:
parameters = {'kernel':('linear', 'rbf'), 'C':[5, 10, 100]}

def hyperparamater_search(params):
  cv = GridSearchCV(estimator = SVC(random_state = 42), param_grid = params, cv = 10 )
  cv.fit(X, y)
  print(cv.best_score_)
  print(cv.best_params_)

In [ ]:
hyperparamater_search(parameters)

0.9636363636363636
{'C': 5, 'kernel': 'linear'}


#**Graded Assignment - 8**

##Question 1

Write a function `compute_GridSearchCV` which accepts the Kernel and regularization parameters as inputs and returns the Mean cross-validated score of the best_estimator, denoted with `best_score_` of the models with the below mentioned hyperparameters:
- Split the Iris dataset into train and test set with 70:30 ratio 
- Import svm.SVC as 'model'
- kernels = ['linear' , 'rbf']
- Regularization = [1,15,25]
- gamma = 'auto'
- Cross Validation = 4
- `random_state=0`

(a) 0.9799075391180654

(b) 0.8182475236540654

(c) 0.7999999995540654

(d) 0.1111111122223444


**(Option a)**

In [ ]:
import numpy as np
import pandas as pd
from sklearn import svm, datasets
iris = datasets.load_iris()
np.random.seed(42)
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3,random_state = 0)

In [ ]:
def COMPUTE_GridSearchCV(kernels, C):
     clf = GridSearchCV(svm.SVC(gamma='auto'), {'C': C, 'kernel': kernels},
                        cv=4, return_train_score=False)
     clf.fit(iris.data, iris.target)
     print(clf.best_score_)
     print(clf.best_params_)

In [ ]:
kernels = ['linear', 'rbf']
C = [1,15,25]
COMPUTE_GridSearchCV(kernels, C)

0.9799075391180654
{'C': 1, 'kernel': 'linear'}


## Question 2 and 3

**Read the instructions given below to answer the two questions given below.**

Split the `Social_Network_Ads` dataset (https://drive.google.com/file/d/1qUa1GlG4X4ZY_4E0e7jPR-z7AG7NIDbE/view?usp=sharing) into training and test set in 75:25 ratio.
- Fit and transform the train and test set of the feature matrix by applying `StandardScaler` transformer.
- Fit a linear SVM (with `random_state = 0`and `linear` kernel) to training data. 

**Question 2**

The predicted data returns an `accuracy_score` on test data. Which of the following option represents the calculated `accuracy_score`?

(a) 0.88

(b) 0.99

(c) 0.77

(d)1.20

**Option a**

**Question 3**

Calculate the confusion matrix obtained  from the above predicted data.

(a) [[5  63]
 [ 7 25]]

(b) [[63  5]
 [ 7 25]]

(c) [[63  5]
 [ 25 7]]

(d) [[5  63]
 [ 25 7]]

**Option b**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.random.seed(42)
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
data = pd.read_csv('Social_Network_Ads.csv')


In [ ]:
data.shape

(400, 3)

In [ ]:
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [ ]:
pipe = make_pipeline(StandardScaler(), SVC(kernel = 'linear', random_state = 0))
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.88
[[63  5]
 [ 7 25]]


##Questions 4 and 5

**Question 4**

From the MNIST dataset, consider the first 20,000 data samples as training data and the next 5,000 data samples as test data. Fit a pipeline with MinMaxScaler and a classifier with SVC, linear kernel, one vs rest decision_function_shape and `class_weight=None` to this dataset and answer the following questions.

**What is the sum of the main diagonal elements of the confusion matrix?**

(a) 4523

(b) 4423

(c) 4623

(d) 4693

**Option c**

**Question 5**

Which of the following are the correct values of precision, recall and f1_Score?

(a) Precision: 0.90 
Recall: 0.89 
f1_Score: 0.90 

(b) Precision: 0.99 
Recall: 0.99 
f1_Score: 0.99 

(c) Precision: 0.92 
Recall: 0.92 
f1_Score: 0.92 

(d) Precision: 0.14 
Recall: 0.14 
f1_Score: 0.14 

**Option c**

In [ ]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix, precision_recall_curve
from sklearn.metrics import precision_score, recall_score, classification_report

np.random.seed(42)

In [ ]:
X,y= fetch_openml('mnist_784',version=1,return_X_y=True) 
#it returns Data and label as a pandas dataframe
X = X.to_numpy()
y = y.to_numpy()

X_train = X[0:20000,:]
X_test = X[20000:25000,:]
y_train = y[0:20000]
y_test = y[20000:25000]

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(20000, 784) (5000, 784) (20000,) (5000,)


In [ ]:
# Create a pipeline

pipe_2 = Pipeline([('scaler', MinMaxScaler()),
                         ("classifier", svm.SVC(kernel='linear', decision_function_shape='ovr', C=1, class_weight=None))])

# Fit the estimator , pipeline

pipe_2.fit(X_train,y_train)

# Get the predictions

y_pred = pipe_2.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix : \n', cm)
out = np.sum(np.diag(cm))
out

Confusion matrix : 
 [[469   0   1   0   0   5   1   1   1   0]
 [  1 555   2   4   0   1   1   1   3   0]
 [  5   4 479   6   9   1   3   6   7   1]
 [  3   3  13 462   0  19   0   3   9   4]
 [  2   0   6   0 468   1   2   4   1  16]
 [ 14   0   0  18   2 405   3   2   7   9]
 [  1   2   2   0   6   9 471   0   0   0]
 [  0   2   4   1   7   1   0 483   0   6]
 [  3  10  11  15   0  19   6   3 396   3]
 [  3   6   1   2  21   0   0  26   2 435]]


4623

In [ ]:
print(cm.shape)

(10, 10)


In [ ]:
precisionScore = precision_score(y_test, y_pred, average='micro')
recallSscore = recall_score(y_test, y_pred, average='micro')
f1Score = f1_score(y_test, y_pred, average='micro')

print("Precision: {:.2f} %".format(precisionScore))
print("Recall: {:.2f} %".format(recallSscore))
print("f1_Score: {:.2f} %".format(f1Score))

Precision: 0.92 %
Recall: 0.92 %
f1_Score: 0.92 %


## Question 6

Consider the MNIST dataset, split it into training and test set in 50:50 ratio with `random_state = 42`. Fit a SVM model using pipeline with StandardScalar, SVM classifier `kernel='poly'` and `degree = 3`,  `decision_function_shape='ovr'`and `class_weight='balanced'`, `C=10`. Train the model on training data, and make predictions for test data. Generate the Classification report and choose the correct value for weighted avg of f1_score.

(a) 0.96

(b) 0.97

(c) 0.98

(d) 0.99

**Option b**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 45)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(35000, 784) (35000, 784) (35000,) (35000,)


In [ ]:
pipe_1 = Pipeline([('scaler', StandardScaler()),
                         ("classifier", SVC(kernel='poly', degree = 3, decision_function_shape='ovr', class_weight='balanced', C=10))])
pipe_1.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 SVC(C=10, class_weight='balanced', kernel='poly'))])

In [ ]:
y_pred = pipe_1.predict(X_test)

CR = classification_report(y_test, y_pred)
print('Classification report \n')
print(CR)

Classification report 

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      3415
           1       0.99      0.99      0.99      3854
           2       0.97      0.97      0.97      3484
           3       0.97      0.96      0.97      3550
           4       0.97      0.98      0.97      3450
           5       0.97      0.97      0.97      3133
           6       0.99      0.98      0.98      3494
           7       0.98      0.96      0.97      3692
           8       0.95      0.97      0.96      3429
           9       0.96      0.96      0.96      3499

    accuracy                           0.97     35000
   macro avg       0.97      0.97      0.97     35000
weighted avg       0.97      0.97      0.97     35000



##Question 7
Write the function `compute_score(X_train, y_train, X_test, y_test)` to do the following on the `Iris` dataset-

Write your code keeping in mind:
- Split the Iris dataset into train and test set with 70:30 ratio 
- Import svm.SVC as 'model'
- kernel as 'poly', regularization parameter as 10 and gamma as 'auto'
- Train the 'model' and mark the computed 'score'


(a) 2.0

(b) 1.0

(c) -1.0

(d) -2.0

**Option b**

In [ ]:
import numpy as np
from sklearn import svm, datasets
import json
import random
np.random.seed(42)
iris = datasets.load_iris()
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3,random_state = 42)
def COMPUTE_SCORE(X_train, y_train, X_test, y_test):
  model1 = svm.SVC(kernel='poly',C=10,gamma='auto')
  model1.fit(X_train,y_train)
  score1=model1.score(X_test, y_test)
  return score1
score1 =COMPUTE_SCORE(X_train, y_train, X_test, y_test)
print(score1) 

1.0


##Question 8

Write the function `compute_score(X_train, y_train, X_test, y_test)` to do the following on the `Iris` dataset-

Write your code keeping in mind:
- Split the Iris dataset into train and test set with 70:30 ratio 
- Import svm.SVC as 'model'
- kernel as 'sigmoid', regularization parameter as 25 and gamma as 'auto'
- Train the 'model' and mark the computed 'score'


(a) 0.2666666666666666

(b) 0.9555555555555556

(c) 1.8122222222222222

(d) 2.2111111111111111

**Option a**


In [ ]:
import numpy as np
import pandas as pd
from sklearn import svm, datasets
iris = datasets.load_iris()
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)
def COMPUTE_SCORE(X_train, y_train, X_test, y_test):
  model1 = svm.SVC(kernel='sigmoid',C=25,gamma='auto')
  model1.fit(X_train,y_train)
  score1=model1.score(X_test, y_test)
  return score1
score1 =COMPUTE_SCORE(X_train, y_train, X_test, y_test)
print(score1)

0.28888888888888886


##Question 9

Import the `iris` dataset and drop the rows where `class=Iris-setosa`. Apply a pipeline containing a `MinMaxScaler()`function called`Scaler` and a `svm.svc()` called `classifier`. Split the `iris` dataset into 75:25 ratio with `random_state=0`. Mark the correct precision score.

(a) 0.00

(b) 1.22

(C) 0.96

(d) 2.33

**Option c**


In [ ]:
# Import the libraries for performing classification
from sklearn.datasets import load_iris
df = load_iris(as_frame = True)
df1 = pd.DataFrame(df.data)
df1['classes'] = df['target']

In [ ]:
df.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
id = np.where(df1['classes'] == 0)

id

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),)

In [ ]:
df2 = df1.drop(index = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
df2['classes'].value_counts()

1    50
2    50
Name: classes, dtype: int64

In [ ]:
X = df2.iloc[:,:-1]
y = y = df2.iloc[:,-1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [ ]:
pipe = make_pipeline(MinMaxScaler(), SVC(kernel='linear', decision_function_shape='ovr', C=1, class_weight=None))
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
print('Recall: ', precision_score(y_test, y_pred, average='micro'))

Recall:  0.96
