<a href="https://colab.research.google.com/github/samapatil1729/Machine-Learning-Techniques/blob/main/MLP_WEEK_1_TO_4_programing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week_1


##Graded Assignment

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer

In [ ]:
df = load_breast_cancer()

In [ ]:
print(df.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [ ]:
X,y = load_breast_cancer(as_frame=True, return_X_y=True )

In [ ]:
type(X), type(y)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [ ]:
X.columns


Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension'],
      dtype='object')

###Question 1 

Find shape of the Wisconsin breast cancer data's feature matrix (accessed from sklearn.datasets)



In [ ]:
X.shape, y.shape

((569, 30), (569,))

###Question 2  

How many benign ( B ) tumour cases are present in the Wisconsin breast cancer dataset ?

###Question 3  

How many malignant ( M ) tumour cases are present in the Wisconsin breast cancer dataset.

In [ ]:
item_counts = y.value_counts()
item_counts                     

# 1 - benign ( B ) 
# 0 - malignant ( M )

1    357
0    212
Name: target, dtype: int64

###Instructions for Questions 4-6: 

Use the following code for importing California Housing dataset from sklearn. Also, name the dataset as housing_data and print description of the dataset.



In [ ]:
from sklearn.datasets import fetch_california_housing
housing_data = fetch_california_housing()
print(housing_data.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [ ]:
X,y = fetch_california_housing(as_frame=True, return_X_y=True)

###Question 4  

Find out the shape of the feature matrix in california housing dataset.

In [ ]:
X.shape, y.shape

((20640, 8), (20640,))

###Question 5   

Find out the labels of the first five attributes in california housing dataset. Note, the labels are real-valued.

In [ ]:
y.head(5)

AttributeError: ignored

###Question 6  

Find out the name of the class label in california housing dataset(target matrix)?

In [ ]:
y.name

'MedHouseVal'

##Practice Assignment

###Question 1

Which of the following options are the class names in the iris dataset?

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [ ]:
df = load_iris()

In [ ]:
print(df.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
from sklearn.datasets import make_multilabel_classification

### Question 2  

Generate 200 samples with 10 features for multiple regression problem with 10 outputs and find the shapes of the feature matrix and the label vector.

In [ ]:
X,y = make_multilabel_classification(n_samples = 200, n_features = 10, n_classes= 10)

In [ ]:
X.shape, y.shape

((200, 10), (200, 10))

###Question 3 

Find the shapes of the feature matrix and the label vector for a multilabel classification problem with 200 samples, 10 features, 7 labels and on an average 3 labels per example.

In [ ]:
X,y = make_multilabel_classification(n_samples = 200, n_features = 10, n_classes= 7)

In [ ]:
X.shape, y.shape

((200, 10), (200, 7))

#WEEK_2

##Practice Assignment

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/DataPreprocessingGraded_dataset (1).csv')

###Question 1

How many samples are there in this dataset?

In [ ]:
df.shape

(748, 6)

###Question 2

How many input features are there in this dataset?

In [ ]:
df.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'Target'], dtype='object')

In [ ]:
df['V1'].value_counts()

2.0     171
4.0     156
11.0     84
14.0     76
16.0     63
23.0     50
21.0     44
9.0      20
3.0      13
7.0       8
1.0       7
8.0       6
5.0       6
12.0      6
13.0      5
6.0       5
?         5
0.0       4
10.0      3
15.0      2
18.0      2
38.0      2
20.0      1
39.0      1
25.0      1
17.0      1
26.0      1
74.0      1
40.0      1
35.0      1
22.0      1
72.0      1
Name: V1, dtype: int64

In [ ]:
df['V2'].value_counts()

1.0     158
2.0     112
3.0      87
5.0      62
4.0      61
6.0      52
7.0      42
8.0      31
9.0      24
11.0     22
10.0     14
12.0     14
14.0     13
16.0     12
13.0      9
15.0      5
?         5
17.0      4
24.0      3
22.0      2
19.0      2
20.0      2
21.0      2
34.0      1
41.0      1
26.0      1
44.0      1
50.0      1
43.0      1
38.0      1
18.0      1
46.0      1
33.0      1
Name: V2, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      748 non-null    object 
 1   V2      748 non-null    object 
 2   V3      748 non-null    float64
 3   V4      748 non-null    float64
 4   V5      748 non-null    object 
 5   Target  748 non-null    object 
dtypes: float64(2), object(4)
memory usage: 35.2+ KB


In [ ]:
df.head()

V1    V2       V3    V4        V5 Target
0  2.0  50.0  12500.0  98.0  NEGATIVE    YES
1  0.0  13.0   3250.0  28.0  NEGATIVE    YES
2    ?     ?   4000.0  35.0  NEGATIVE    YES
3    ?  20.0   5000.0  45.0  NEGATIVE    YES
4  1.0  24.0   6000.0  77.0  NEGATIVE     NO

In [ ]:
df.replace('?', np.nan, inplace=True)

In [ ]:
df.head()

V1    V2       V3    V4        V5 Target
0  2.0  50.0  12500.0  98.0  NEGATIVE    YES
1  0.0  13.0   3250.0  28.0  NEGATIVE    YES
2  NaN   NaN   4000.0  35.0  NEGATIVE    YES
3  NaN  20.0   5000.0  45.0  NEGATIVE    YES
4  1.0  24.0   6000.0  77.0  NEGATIVE     NO

In [ ]:
df['V1'] = pd.to_numeric(df['V1'])
df['V2'] = pd.to_numeric(df['V2'])   
df['V5'].replace(['NEGATIVE','POSITIVE'],[0,1], inplace = True)              

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   V1      743 non-null    float64
 1   V2      743 non-null    float64
 2   V3      748 non-null    float64
 3   V4      748 non-null    float64
 4   V5      748 non-null    int64  
 5   Target  748 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 35.2+ KB


In [ ]:
df.describe()

V1          V2            V3          V4     V5
count  743.000000  743.000000    748.000000  748.000000  748.0
mean     9.562584    5.464334   1378.676471   34.282086    0.0
std      8.093527    5.799759   1459.826781   24.376714    0.0
min      0.000000    1.000000    250.000000    2.000000    0.0
25%      3.000000    2.000000    500.000000   16.000000    0.0
50%      8.000000    4.000000   1000.000000   28.000000    0.0
75%     14.000000    7.000000   1750.000000   50.000000    0.0
max     74.000000   50.000000  12500.000000   98.000000    0.0

In [ ]:
df.Target.unique()

array(['YES', 'NO'], dtype=object)

In [ ]:
df['Target'].value_counts()

NO     570
YES    178
Name: Target, dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer

In [ ]:
X = df.iloc[:, 0:2]

In [ ]:
X

V1    V2
0     2.0  50.0
1     0.0  13.0
2     NaN   NaN
3     NaN  20.0
4     1.0  24.0
..    ...   ...
743  23.0   2.0
744  21.0   2.0
745  23.0   3.0
746  39.0   1.0
747  72.0   1.0

[748 rows x 2 columns]

In [ ]:
si = SimpleImputer(missing_values = np.nan, strategy = 'median')
si = si.fit(X)
s = si.transform(X)

In [ ]:
s.mean(axis=0)

array([9.55213904, 5.45454545])

In [ ]:
si = SimpleImputer(missing_values = np.nan, strategy = 'mean')
si = si.fit(X)
v = si.transform(X)

In [ ]:
v.mean(axis=0)

array([9.56258412, 5.46433378])

In [ ]:
K = KNNImputer(n_neighbors=3)
K = K.fit(X)
k = K.transform(X)

In [ ]:
k.mean(axis=0)

array([9.52570755, 5.52423931])

#WEEK_3 

##Practice Assignment 3 

In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn. model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import ShuffleSplit
from sklearn.linear_model import LinearRegression

In [ ]:
df = fetch_california_housing(as_frame = True)

In [ ]:
X, y = fetch_california_housing(as_frame = True, return_X_y=True)

In [ ]:
X.shape, y.shape

((20640, 8), (20640,))

In [ ]:
print(df.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [ ]:
df.data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB


In [ ]:
df.data.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [ ]:
X_tr, X_te, y_tr, y_te = train_test_split(X,y,test_size = 0.2, shuffle = False, random_state = 0)

In [ ]:
X_te.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
16512  2.6368      34.0  5.769022   1.051630      1310.0  3.559783     37.72   
16513  3.6378      17.0  5.432075   1.022642      1802.0  3.400000     37.81   
16514  2.1186      28.0  4.707581   1.039711      1719.0  3.102888     37.80   
16515  2.1250      37.0  4.919431   1.052133       521.0  2.469194     37.80   
16516  2.9950      18.0  4.750988   0.984190      1531.0  3.025692     37.81   

       Longitude  
16512    -121.22  
16513    -121.22  
16514    -121.22  
16515    -121.22  
16516    -121.21

In [ ]:
X_tr.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [ ]:
y_tr.mean(axis=0)

2.02067031310562

In [ ]:
y_te.median(axis=0)

2.1475

In [ ]:
lin_reg_pipeline = Pipeline([('feture_scaling', StandardScaler()), ('lin_reg', LinearRegression())])
lin_reg_pipeline.fit(X_tr,y_tr)

Pipeline(steps=[('feture_scaling', StandardScaler()),
                ('lin_reg', LinearRegression())])

In [ ]:
lin_reg_pipeline[-1].coef_

array([ 0.83817967,  0.12032096, -0.32135834,  0.36456599, -0.00170674,
       -0.04524631, -0.87994217, -0.82634126])

In [ ]:
lin_reg_pipeline[-1].intercept_

2.020670313105614

##Graded Assignment 3

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.model_selection import ShuffleSplit
from sklearn.metrics import r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import fetch_california_housing
from sklearn.metrics import mean_squared_error
from sklearn.metrics import explained_variance_score
from sklearn.metrics import max_error 
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import SGDRegressor

In [ ]:
df = fetch_california_housing()

In [ ]:
X,y = fetch_california_housing(as_frame = True, return_X_y = True)

In [ ]:
X_tr, X_te, y_tr, y_te = train_test_split(X,y,test_size = 0.2, shuffle = False, random_state = 0)

In [ ]:
lin_reg_pipeline = Pipeline([('feture_scaling', StandardScaler()), ('lin_reg', LinearRegression())])

In [ ]:
lin_reg_pipeline.fit(X_tr, y_tr)

Pipeline(steps=[('feture_scaling', StandardScaler()),
                ('lin_reg', LinearRegression())])

In [ ]:
y_pred = lin_reg_pipeline.predict(X_te)
y_pred

array([1.31635001, 1.58760352, 1.11744227, ..., 0.14384532, 0.29510241,
       0.49760107])

In [ ]:
r2_score = r2_score(y_te, y_pred)
r2_score

0.6605140591531992

In [ ]:
rmse = (mean_squared_error(y_te, y_pred))**0.5
rmse


0.7033383507521878

In [ ]:
Var_score = explained_variance_score(y_te, y_pred)
Var_score

0.6605500501742703

In [ ]:
Max_error = max_error(y_te, y_pred)
Max_error

7.260453292958372

In [ ]:
mae = mean_absolute_error(y_te, y_pred)
mae

0.5168526993787042

In [ ]:
mse = mean_squared_error(y_te, y_pred)
mse

0.49468483563880755

In [ ]:
sgd_reg_pipeline = Pipeline([('feature_scaling', StandardScaler()),('sgd_reg', SGDRegressor())])
sgd_reg_pipeline.fit(X_tr, y_tr)

Pipeline(steps=[('feature_scaling', StandardScaler()),
                ('sgd_reg', SGDRegressor())])

In [ ]:
sgd_reg_pipeline[-1].intercept_


array([2.00768268])

In [ ]:
sgd_reg_pipeline[-1].coef_

array([ 0.80697821,  0.13524165, -0.1931643 ,  0.32967264,  0.04669683,
       -1.39726303, -0.91065244, -0.79887059])

#WEEK_4

##Practice Assignment

###Question 1

In [ ]:
def compute_explained_variance(y_true, y_pred):
  from sklearn.metrics import explained_variance_score
  return explained_variance_score(y_true, y_pred)

In [ ]:
#from sklearn.metrics import explained_variance_score
y_true = [7, 4, 9, 4] 
y_pred = [8, 7, 12, 5] 
compute_explained_variance(y_true, y_pred)

0.7777777777777778

###Question 2

Write a function compute_score(X_train, y_train, X_test, y_test) to compute the score of SGDRegressor for predicting the house price of California Housing dataset. Write your code based on the following keypoints:

Split the California housing dataset into train and test set with 70:30 ratio and random_state = 1

Import StandardScaler for scaling X_train and X_test to X_train_norm and X_test_norm with_mean = True and with_std = True

Import SGDRegressor as 'model' with hyperparamters loss as 'squared_error', penalty as 'l1' and alpha as 0.01 and random_state = 1

Train the 'model' and compute the 'score' on test data
Enter the value of the 'score' computed from the function 'compute_score'. (Enter your answer in four decimal places)

(NAT)

Answer: 0.5951 (Range: 0.59 - 0.6)


In [7]:
import numpy as np
import sklearn
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split

In [8]:
X,y = fetch_california_housing(as_frame = True, return_X_y = True)
X_tr, X_te, y_tr, y_te = train_test_split(X,y,test_size = 0.3, random_state = 1)

In [19]:
def compute_score(X_train, y_train, X_test, y_test):
  from sklearn.preprocessing import StandardScaler
  from sklearn.linear_model import SGDRegressor

  scaler = StandardScaler(with_mean=True, with_std=True)
  X_train_norm =scaler.fit_transform(X_train)
  X_test_norm = scaler.transform(X_test)

  model = SGDRegressor(loss = 'squared_error', penalty = 'l1', alpha = 0.01, random_state = 1 )
  model.fit(X_train_norm,y_train)

  score = model.score(X_test_norm, y_test)
  return score
  #Your code ends here
  pass

In [20]:
score = compute_score(X_tr, y_tr, X_te, y_te)
score

0.5951040704728554

##Graded Assignment -4 

###Question 1
Write a function k_fold_cv(X) to run 2-fold cross validation repeated 2 times for the array X = [[1, 2], [3, 4], [1, 2], [3, 4]] which will return a concatenated array combining the training and testing dataset. Set random_state=1 in your code. Which of the following options denote the concatenated array?

(a) [0 2 1 3]

(b) [1 0 3 2]

(c) [2 3 0 1]

(d) [1 3 1 2]

(MCQ) Option 1

In [21]:
import numpy as np
import random
from sklearn.model_selection import RepeatedKFold

In [26]:
X = [[1, 2], [3, 4], [1, 2], [3, 4]] 
def k_fold_cv(X, random_state = 1):
  ans = RepeatedKFold(n_splits = 2, n_repeats = 2, random_state = 1 )
  spit = 1
  for train, test in ans.split(X):
    spit += 1
  array1 = np.append(train, test)
  return array1
pass
EOP = str(k_fold_cv(X,random_state = 1))
print(EOP)

[0 2 1 3]


Write a code to predict the house price of California Housing dataset using GridSearchCV.

Write your code based on the following keypoints:

Split the California housing dataset into train and test set with 70:30 ratio with random_state = 1.
Import StandardScaler for scaling X_train and X_test to X_train_norm and X_test_norm with_mean = True and with_std = True
Import SGDRegressor with random_state = 1
Pass SGDRegressor through GridSearchCV
Hyperparamter tuning to be done over
loss as 'squared_error' or 'huber'
penalty as 'l1' or 'l2'
alpha as 0.1, 0.01, 0.001
maximum number of passes as [1000,2000,5000]
Cross Validation = 4
Train the 'model' and compute the 'score' on test data
Question 1: Enter the value of the 'score'. (Enter your answer in four decimal places)

(NAT) Answer: 0.5951 (Range : 0.589-0.599)

Question 2: Enter the value of the best alpha obtained.

(NAT) Answer: 0.01

Question 3: Enter the value of the best maximum number of passes obtained.

(NAT) Answer: 1000

In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.stats import loguniform
from scipy.stats import uniform

from sklearn.datasets import fetch_california_housing
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import LassoCV
from sklearn.linear_model import Ridge
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import SGDRegressor

from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error

from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import validation_curve
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import StandardScaler

from sklearn.pipeline import Pipeline

In [29]:
np.random.seed(306)

In [31]:
X,y = fetch_california_housing(as_frame = True, return_X_y = True)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size = 0.3, random_state = 1)

In [33]:
X_tr.shape, X_te.shape

((14448, 8), (6192, 8))

In [36]:
scaler = StandardScaler(with_mean = True, with_std = True)
X_tr_norm = scaler.fit_transform(X_tr)
X_te_norm = scaler.transform(X_te)

In [37]:
sgd = SGDRegressor(random_state = 1)
param = {'max_iter': [1000,2000,5000], 'alpha':[0.1, 0.01, 0.001], 'loss': ['squared_error', 'huber'], 'penalty':['l2', 'l1']}

In [39]:
grid = GridSearchCV(estimator = sgd, param_grid = param, cv = 4)

In [43]:
grid.fit(X_tr_norm, y_tr)

GridSearchCV(cv=4, estimator=SGDRegressor(random_state=1),
             param_grid={'alpha': [0.1, 0.01, 0.001],
                         'loss': ['squared_error', 'huber'],
                         'max_iter': [1000, 2000, 5000],
                         'penalty': ['l2', 'l1']})

###Question 2

Enter the value of the 'score'. (Enter your answer in four decimal places)

In [44]:
test_score = grid.score(X_te_norm, y_te)
test_score

0.5951040704728554

###Question 3,4

Enter the value of the best alpha obtained.    
 
Ans: alpha = 0.01

Enter the value of the best maximum number of passes obtained.

Ans: 1000

In [46]:
grid.best_params_

{'alpha': 0.01, 'loss': 'squared_error', 'max_iter': 1000, 'penalty': 'l1'}

Write a code to predict the house price of California Housing dataset using GridSearchCV.

Write your code based on the following keypoints:

Split the California housing dataset into train and test set with 70:30 ratio with  random_state = 1
.
Import StandardScaler for scaling X_train and X_test to X_train_norm and X_test_norm with_mean = True and with_std = True

Pass Ridge Regression Model through GridSearchCV
Hyperparamter tuning to be done over alpha
 as 0.5,0.1,0.05,0.01,0.005,0.001
With or without intercept

Cross Validation = 4

Train the 'model' and compute the 'score' on test data

In [48]:
param1 = {'alpha': [0.5,0.1,0.05,0.01,0.005,0.001]}
rdg_reg = Ridge()
grid1 = GridSearchCV(estimator = rdg_reg, param_grid = param1 , cv = 4)
grid1.fit(X_tr_norm, y_tr)

GridSearchCV(cv=4, estimator=Ridge(),
             param_grid={'alpha': [0.5, 0.1, 0.05, 0.01, 0.005, 0.001]})

###Question 5

In [49]:
grid1.score(X_te_norm, y_te)

0.597145061224877

###Question 6

In [50]:
grid1.best_params_

{'alpha': 0.5}

Write a code to predict the house price of California Housing dataset using GridSearchCV.

Write your code based on the following keypoints:
- Split the California housing dataset into train and test set with 60:40 ratio with `random_state = 1`.
- Import StandardScaler for scaling X_train and X_test to X_train_norm and X_test_norm `with_mean = True` and `with_std = True`
- Pass Lasso Model through GridSearchCV
- Hyperparamter tuning to be done over
  - `alpha` as 0.5,0.1,0.05,0.01,0.005,0.001
  - With or without intercept
- Cross Validation = 6
- Train the 'model' and compute the 'score' on test data

In [51]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size = 0.4, random_state = 1)


In [52]:
X_tr.shape, X_te.shape

((12384, 8), (8256, 8))

In [53]:
sc1 = StandardScaler(with_mean = True, with_std = True)
X_tr_norm1 = sc1.fit_transform(X_tr)
X_te_norm1 = sc1.transform(X_te)

In [54]:
lasso_grid = Lasso()

In [55]:
param3 = {'alpha': [0.5,0.1,0.05,0.01,0.005,0.001]}

In [56]:
grid3 = GridSearchCV(estimator = lasso_grid, param_grid = param3 , cv = 6)

In [57]:
grid3.fit(X_tr_norm1, y_tr)

GridSearchCV(cv=6, estimator=Lasso(),
             param_grid={'alpha': [0.5, 0.1, 0.05, 0.01, 0.005, 0.001]})

###Question 7

Which of the following is the 'score' computed by your code?

(a) 0.6065831805608592

(b) 0.806583116745592

(c) 0.1224876959714506

(d) 0.1214876325845632

(MCQ) Answer: (Option a)

In [59]:
grid3.score(X_te_norm1, y_te)

0.6047829320240279

### Question 8

Enter the value of the best alpha obtained.

In [60]:
grid3.best_params_

{'alpha': 0.005}